config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :events
  resources :event_users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'profile', to: 'users#show'
  # Defines the root path route ("/")
  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_users, foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :event_users, source: :attendee

  scope :past, -> { where("date < :today", { today: Date.today }) }
  scope :upcoming, -> { where("date >= :today", { today: Date.today }) }

  # def past
  #   @past = Event.where("date < :today", { today: Date.today }).order(date: :asc)
  # end

  # def upcoming
  #   @upcoming = Event.where("date >= :today", { today: Date.today }).order(date: :asc)
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @events = Event.order(date: :asc)
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to profile_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= form_with model: @event do |f| %>
  <%= f.label :title, "Title" %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :description, "Description" %><br>
  <%= f.text_area :description %><br><br>
  <%= f.label :date, "Date" %><br>
  <%= f.date_select :date %><br><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<h2>Upcoming Events</h2>
<% Event.upcoming.order(date: :asc).each do |event| %>
  <ul>  
    <li>
      <h3><%= event.title %></h3>
      <%= event.description %><br>
      <%= event.date %><br>
      <%= "Creator ID:" %>
      <%= event.creator.id %><br>
      <% user = user_signed_in? ? current_user.id : nil %>
      <% attend = EventUser.where(attended_event_id: event.id, attendee_id: user).blank? ? true : false %>
      <% if attend == true %>
        <%= button_to "Attend this event", event_users_path, params: {id: event.id}, method: :post %>
      <% else %>
        <%= button_to "Revoke RSVP?", event_user_path(event.id), method: :delete %>
      <% end %>
      <%= link_to "See Event Attendees", event_path(event.id), method: :get %>
    </li>
  </ul>
<% end %>
<h2>Past Events</h2>
<% Event.past.order(date: :asc).each do |event| %>
  <ul>  
    <li>
      <h3><%= event.title %></h3>
      <%= event.description %><br>
      <%= event.date %><br>
      <%= "Creator ID:" %>
      <%= event.creator.id %><br>
      <%= link_to "See Event Attendees", event_path(id: event.id, past: "past"), method: :get %>
    </li>
  </ul>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>
  <%= f.label :title, "Title" %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :description, "Description" %><br>
  <%= f.text_area :description %><br><br>
  <%= f.label :date, "Date" %><br>
  <%= f.date_select :date %><br><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<%= @event.description %><br>
<%= @event.date %><br>
<%= "Creator ID:" %>
<%= @event.creator.id %><br>
<% unless params[:past] == "past" %>
  <%= button_to "Attend this event", event_users_path, params: {id: @event.id}, method: :post %><br><br>
<% end %>

<%= "Attendees: " %><br>

<% @attendees.each do |attendee| %>
  <ul>  
    <li>
      <%= attendee.first_name %>
      <%= attendee.last_name %>
    </li>
  </ul>
<% end %>